import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { IconHome, IconUser, IconBriefcase } from "@tabler/icons-react";
import { Tabs } from "@/components/navbar";
import Link from "next/link";
import { Roboto } from "next/font/google";
import { Download } from "lucide-react";
import { IconFolder } from "@tabler/icons-react";


export const metadata: Metadata = {
  title: "My Website",
  description: "Responsive Next.js Website",
};

// 👇 NEW correct way
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // normal, medium, bold
  variable: "--font-roboto",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata1: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // 👇 Tabs = Links
  const tabs = [
  { 
    title: "Home", 
    value: "home", 
    href: "/", 
    icon: <IconHome className="h-5 w-5" /> 
  },
  { 
    title: "About", 
    value: "about", 
    href: "/About", 
    icon: <IconUser className="h-5 w-5" /> 
  },
  { 
    title: "Projects", 
    value: "projects", 
    href: "/Projects", 
    icon: <IconFolder className="h-5 w-5" /> 
  },
  { 
    title: "Work Experience", 
    value: "work", 
    href: "/WorkExperience", 
    icon: <IconBriefcase className="h-5 w-5" /> 
  },
  {
  title: "Resume",
  value: "resume",
  href: "https://docs.google.com/document/d/1FuMUe5XMI-K4YbX5uXHyGhbHj6CV4LZMbcbZipX0uCc/preview",
  icon: <Download className="h-5 w-5" />,
}
];


 return (
  <html lang="en">
 
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black min-h-screen flex flex-col`}
    >
      {/* Tabs act as navigation */}
      <div className="flex justify-center p-4">
        <Tabs tabs={tabs} />
      </div>
      
      

      {/* Page content */}
      <main className="flex-1 p-0 m-0">{children}</main>

      {/* Footer */}
      <footer className="flex justify-center items-center text-sm bg-blue-200 text-black py-2 mt-3 gap-2">
        <span>© {new Date().getFullYear()} Advika Sawant.</span>
        <span>All rights reserved.</span>
      </footer>
    </body>
  </html>
);

}
